config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Defines the authentication routes.
  get "login", to: "authentication#login"
  patch "login", to: "authentication#totp_handler"
  post "login", to: "authentication#login_post"
  delete "logout", to: "authentication#logout"
  get "forgot_password", to: "authentication#forgot_password_enter_email"
  post "forgot_password", to: "authentication#forgot_password_enter_email_post"
  get "forgot_password/:token", to: "authentication#forgot_password_remainder"
  post "forgot_password/:token", to: "authentication#forgot_password_remainder_post"
  get "register", to: "authentication#register_enter_email"
  post "register", to: "authentication#register_enter_email_post"
  get "register/:token", to: "authentication#register_remainder"
  post "register/:token", to: "authentication#register_remainder_post"
  get "email/update/:token", to: "authentication#email_change_token_click"

  # Defines the Turbo components (used when a component is too slow to load with the rest of the page or encapsulates a lot of logic).
  get 'components/user_list', to: 'turbo_components#user_list'
  get 'components/skeet_media_frame/:frame_id/:url', to: 'turbo_components/media_frame#skeet_media_frame', constraints: { frame_id: /[^\/]+/, url: /[^\/]+/ }
  patch 'components/skeet_action', to: 'turbo_components/skeet_action#skeet_action'
  get 'components/home_feed/:did', to: 'turbo_components#home_feed', constraints: { did: /[^\/]+/ }
  get 'components/user_settings', to: 'turbo_components/settings#user_settings'
  patch 'components/user_settings', to: 'turbo_components/settings#user_settings_patch'
  get 'components/bluesky_user_settings/:did', to: 'turbo_components/settings#bluesky_user_settings', constraints: { did: /[^\/]+/ }
  patch 'components/bluesky_user_settings/:did', to: 'turbo_components/settings#bluesky_user_settings_patch', constraints: { did: /[^\/]+/ }
  delete 'components/bluesky_user_settings/:did', to: 'turbo_components/settings#bluesky_user_settings_delete', constraints: { did: /[^\/]+/ }

  # Defines a VERY slim API for the AJAX calls.
  get "ajax/notification_count/:did", to: "ajax#notification_count"
  get "ajax/home_feed", to: "ajax#home_feed"

  # Defines the homepage routes.
  get "home", to: "home#home"
  get "home/new", to: "home#new_user"
  post "home/new", to: "home#new_user_post"
  get "home/:did", to: "home#home_did"
  get "home/:did/settings", to: "home#settings_skeleton"
  get "accept_invite/:code", to: "home#accept_invite"

  # Handle post viewing.
  get "post/:identifier/:post_id", to: "post#view", constraints: { identifier: /[^\/]+/, post_id: /[^\/]+/ }
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
    skip_before_action :user_must_authenticate!
    before_action :user_must_not_authenticate!, except: [:email_change_token_click, :logout]

    CONSTANT_TIME_BCRYPT_HASH = BCrypt::Password.create('1234567890')

    def login; end

    def totp_handler
        # Get the half token.
        half_token = HalfToken.resolve_token(params[:half_token])
        if half_token.nil?
            # It probably expired. Re-render the login page.
            return render 'login'
        end

        # Get the user.
        user = half_token.user

        # Get the TOTP code.
        if user.totp_secret.present?
            res = validate_totp(user)
            if !res
                @error = 'Invalid TOTP code.'
                return render 'login_totp', status: :unauthorized
            end
        end

        # Upgrade the token.
        user_token = half_token.upgrade!
        cookies[:user_token] = {
            value: user_token,
            expires: 6.days.from_now, # Probably best to kill the token before it actually dies.
        }

        # End the auth flow.
        end_of_auth_flow
    end

    def login_post
        # Get the email and password.
        email = params[:email]
        password = params[:password]

        # Find the user.
        user = User.find_by_email(email)
        if user.nil?
            @error = 'Invalid email or password.'

            # Compare the password to the constant time hash. This is to prevent
            # timing attacks.
            BCrypt::Password.new(CONSTANT_TIME_BCRYPT_HASH) == password

            return render 'login', status: :unauthorized
        end

        # Check the password.
        if !user.authenticate(password)
            @error = 'Invalid email or password.'
            return render 'login', status: :unauthorized
        end

        # If the user has a TOTP secret, then render the TOTP page and make a half token.
        if user.totp_secret.present?
            params[:half_token] = HalfToken.create!(user: user).token
            return render 'login_totp'
        end

        # Create a user token.
        user_token = UserToken.create!(user: user)
        cookies[:user_token] = {
            value: user_token.token,
            expires: 6.days.from_now, # Probably best to kill the token before it actually dies.
        }

        # End the auth flow.
        end_of_auth_flow
    end

    def logout
        # Delete the cookie.
        cookies.delete(:user_token)

        # Call the logout method on the user.
        user.logout! unless user.nil?

        # Redirect to the root.
        redirect_to '/', status: :see_other
    end

    def forgot_password_enter_email; end

    def forgot_password_enter_email_post
        # If email is blank, then re-render the page.
        if params[:email].blank?
            render 'forgot_password_enter_email'
            return
        end

        # Find the user by email.
        user = User.find_by_email(params[:email])
        if user.nil?
            # The user doesn't exist but we can't tell the user that.
            @maybe_successful = true
            return render 'forgot_password_enter_email'
        end

        # Create a password change request.
        UserPasswordChangeRequest.create!(user: user)
        @maybe_successful = true
        render 'forgot_password_enter_email'
    end

    def forgot_password_remainder
        x = UserPasswordChangeRequest.resolve_token!(params[:token])
        @has_totp = x.user.totp_secret.present?
    end

    def forgot_password_remainder_post
        # Get the password change request.
        token = UserPasswordChangeRequest.resolve_token!(params[:token])
        @has_totp = token.user.totp_secret.present?

        # Check if TOTP is valid if relevant.
        if @has_totp
            res = validate_totp(token.user)
            if !res
                @error = 'Invalid TOTP code.'
                return render 'forgot_password_remainder', status: :unauthorized
            end
        end

        # Update the password.
        token.user.update(password: params[:password], password_confirmation: params[:password_confirmation])
        if token.user.errors.any?
            @error = token.user.errors.full_messages.first
            return render 'forgot_password_remainder', status: :bad_request
        end

        # Delete the token.
        token.destroy!

        # Redirect to the login page.
        redirect_to '/login'
    end

    def register_enter_email; end

    def register_enter_email_post
        # Try and create a new user email confirmation.
        res = NewUserEmailConfirmation.create(email: params[:email])
        if res.errors.any?
            # Check if the error is not that the email is already used by another user.
            unless res.user_owning_email_limiting_factor
                @error = res.errors.full_messages.first
                return render 'register_enter_email', status: :bad_request
            end
        end

        # Render the register enter email page.
        @maybe_successful = true
        render 'register_enter_email'
    end

    def register_remainder
        # Make sure the token is valid.
        NewUserEmailConfirmation.resolve_token!(params[:token])
    end

    def register_remainder_post
        # Get the token.
        token = NewUserEmailConfirmation.resolve_token!(params[:token])

        # Create the user.
        user = User.create(email: token.email, password: params[:password], password_confirmation: params[:password_confirmation])
        if user.errors.any?
            @errors = user.errors.full_messages.join('\n')
            return render 'register_remainder', status: :bad_request
        end

        # Destroy the token.
        token.destroy!

        # Create a user token.
        user_token = UserToken.create!(user: user)
        cookies[:user_token] = {
            value: user_token.token,
            expires: 6.days.from_now, # Probably best to kill the token before it actually dies.
        }

        # End the auth flow.
        end_of_auth_flow
    end

    def email_change_token_click
        token = UserEmailUpdateRequest.resolve_token!(params[:token])
        token.user.update(email: token.email)
        if token.user.errors.any?
            # Render the first error.
            @error = token.user.errors.full_messages.first
            return render 'email_change_token_click_error', status: :bad_request
        end
        token.destroy!
        render 'email_change_token_click'
    end

    private

    def end_of_auth_flow
        # Make sure redirect_to is a path and not a url.
        redirect_to = params[:redirect_to]
        redirect_to = nil if redirect_to.blank?
        redirect_to = URI.parse(redirect_to).path if redirect_to.present?

        # Redirect to the path.
        redirect_to redirect_to || "/home"
    end

    def user_must_not_authenticate!
        end_of_auth_flow if @user.present?
    end

    def format_totp_code(code)
        return code unless code.is_a?(String)

        # Remove all non-digit characters.
        code = code.gsub(/\D/, '')

        # Return the code.
        code
    end

    def validate_totp(user)
        totp_code = format_totp_code(params[:totp_code])
        totp = ROTP::TOTP.new(user.totp_secret, issuer: 'Gemsky', drift_behind: 30)
        if !totp.verify(totp_code)
            # Downcase and strip the code.
            totp_code = params[:totp_code].downcase.strip

            # Check if the code is a recovery code.
            recovery_code = TotpRecoveryCode.find_by(user: user, code: totp_code)
            if recovery_code.nil?
                # It's not a recovery code. Re-render the login page.
                return false
            end

            # Delete the recovery code.
            recovery_code.destroy!
        end
        return true
    end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/views/authentication/email_change_token_click.html.erb
<p class="text-4xl text-center">
    <%= icon 'fa-solid', 'check-circle' %>
</p>

<h1 class="mt-4 text-center">
    Your e-mail address was updated successfully!
</h1>

app/views/authentication/email_change_token_click_error.html.erb
<p class="text-4xl text-center">
    <%= icon 'fa-solid', 'times-circle' %>
</p>

<h1 class="mt-4 text-center">
    Failed to update your e-mail address: <code><%= @error %></code>
</h1>

app/views/authentication/forgot_password_enter_email.html.erb
<%= render FormHeaderComponent.new(
    title: 'Change Password',
    description: 'Please enter your email address below to change your password.',
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :post, data: {turbo: false} do %>
        <% if @maybe_successful %>
            <%= render NotificationComponent.new(
                type: 'success',
                body: ['If the e-mail address is attached to a Gemsky user, a password reset was sent.'],
            ) %>
        <% end %>

        <%= render InputComponent.new(
            name: 'email',
            label: 'E-mail Address',
            type: 'email',
            value: params[:email],
        ) %>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'submit',
                label: 'Submit',
                type: 'submit',
                icon: 'envelope',
            ) %>
        </div>
    <% end %>
<% end %>

app/views/authentication/forgot_password_remainder.html.erb
<%
    part = '.'
    part = ' and TOTP code.' if @has_totp
%>
<%= render FormHeaderComponent.new(
    title: 'Change Password',
    description: "Please enter your new password#{part}",
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :post, data: {turbo: false} do %>
        <% unless @error.nil? %>
            <%= render NotificationComponent.new(
                type: 'error',
                body: [@error],
            ) %>
        <% end %>

        <%= render InputComponent.new(
            name: 'password',
            label: 'Password',
            type: 'password',
        ) %>

        <%= render InputComponent.new(
            name: 'password_confirmation',
            label: 'Password Confirmation',
            type: 'password',
        ) %>

        <% if @has_totp %>
            <%= render InputComponent.new(
                name: 'totp_code',
                label: 'TOTP or Recovery Code',
                type: 'text',
            ) %>
        <% end %>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'submit',
                label: 'Submit',
                type: 'submit',
                icon: 'check',
            ) %>
        </div>
    <% end %>
<% end %>

app/views/authentication/login.html.erb
<%= render FormHeaderComponent.new(
    title: 'Welcome to Gemsky!',
    description: 'Please enter your email address and password or register to continue.',
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :post, data: {turbo: false} do %>
        <% unless @error.nil? %>
            <%= render NotificationComponent.new(
                type: 'error',
                body: [@error],
            ) %>
        <% end %>

        <%= render InputComponent.new(
            name: 'email',
            label: 'E-mail Address',
            type: 'email',
            value: params[:email],
        ) %>

        <%= render InputComponent.new(
            name: 'password',
            label: 'Password',
            type: 'password',
        ) %>

        <p class="mt-6 text-center">
            <%= link_to 'Forgot your password?', forgot_password_path %>
        </p>

        <p class="mt-2 text-center">
            Don't have a user?
            <%= link_to 'Register here!', register_path %>
        </p>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'login',
                label: 'Login',
                type: 'submit',
                icon: 'sign-in-alt',
            ) %>
        </div>
    <% end %>
<% end %>

app/views/authentication/login_totp.html.erb
<%= render FormHeaderComponent.new(
    title: 'One more thing!',
    description: 'Please enter your TOTP token below.',
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :patch, data: {turbo: false} do |form| %>
        <% unless @error.nil? %>
            <%= render NotificationComponent.new(
                type: 'error',
                body: [@error],
            ) %>
        <% end %>

        <%= form.hidden_field :half_token, value: params[:half_token] %>

        <%= render InputComponent.new(
            name: 'totp_code',
            label: 'Authenticator or Backup Code',
        ) %>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'submit',
                label: 'Submit',
                type: 'submit',
                icon: 'check',
            ) %>
        </div>
    <% end %>
<% end %>

app/views/authentication/register_enter_email.html.erb
<%= render FormHeaderComponent.new(
    title: 'Register',
    description: 'Please enter your email address below to register.',
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :post, data: {turbo: false} do %>
        <% unless @error.nil? %>
            <%= render NotificationComponent.new(
                type: 'error',
                body: [@error],
            ) %>
        <% end %>

        <% if @maybe_successful %>
            <%= render NotificationComponent.new(
                type: 'success',
                body: ['If the e-mail address is not attached to a Gemsky user, a link was sent to your email.'],
            ) %>
        <% end %>

        <%= render InputComponent.new(
            name: 'email',
            label: 'E-mail Address',
            type: 'email',
            value: params[:email],
        ) %>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'submit',
                label: 'Submit',
                type: 'submit',
                icon: 'envelope',
            ) %>
        </div>
    <% end %>
<% end %>

app/views/authentication/register_remainder.html.erb
<%= render FormHeaderComponent.new(
    title: 'Register',
    description: 'Please enter the password you wish to use below.',
) %>

<%= render DesktopSmallerViewComponent.new do %>
    <%= form_with method: :post, data: {turbo: false} do %>
        <% unless @errors.nil? %>
            <%= render NotificationComponent.new(
                type: 'error',
                body: @errors,
            ) %>
        <% end %>

        <%= render InputComponent.new(
            name: 'password',
            label: 'Password',
            type: 'password',
        ) %>

        <%= render InputComponent.new(
            name: 'password_confirmation',
            label: 'Password Confirmation',
            type: 'password',
        ) %>

        <div class="mt-5 text-center">
            <%= render ButtonComponent.new(
                name: 'submit',
                label: 'Create User',
                type: 'submit',
                icon: 'plus',
            ) %>
        </div>
    <% end %>
<% end %>